
group-offset: 1

bootstrap:
  servers: 192.168.42.1:9093

topic:
  bet : bet
  wallet : wallet
  bmc : bmc

# consumer
enable:
  auto:
    commit: false
auto:
  offset:
    reset: earliest

key:
  serializer: org.apache.kafka.common.serialization.StringSerializer
  deserializer: org.apache.kafka.common.serialization.StringDeserializer

value:
  serializer: com.casumo.bet.events.control.EventSerializer
  deserializer: com.casumo.bet.events.control.EventDeserializer

# producer
acks: all

retries: 0
batch:
  size: 16384
linger:
  ms: 0

buffer:
  memory: 33554432

